INSERT INTO skills_dict (skill_name, category, aliases_json, weight) VALUES
('Java', 'Programming', '["J2EE", "Core Java"]', 1.0),
('Python', 'Programming', '[]', 1.0),
('C++', 'Programming', '["CPP"]', 1.0),
('C#', 'Programming', '["CSharp"]', 1.0),
('JavaScript', 'Programming', '["JS"]', 1.0),
('TypeScript', 'Programming', '["TS"]', 1.0),
('Kotlin', 'Programming', '[]', 1.0),
('Swift', 'Programming', '[]', 1.0),
('Go', 'Programming', '["Golang"]', 1.0),
('Rust', 'Programming', '[]', 1.0),
('PHP', 'Programming', '[]', 1.0),
('Ruby', 'Programming', '[]', 1.0),
('Scala', 'Programming', '[]', 1.0),
('R', 'Programming', '[]', 1.0),
('MATLAB', 'Programming', '[]', 1.0),
('Spring Boot', 'Framework', '["SpringBoot", "Spring"]', 1.0),
('Spring MVC', 'Framework', '[]', 1.0),
('Hibernate', 'Framework', '[]', 1.0),
('React', 'Framework', '["ReactJS", "React.js"]', 1.0),
('Angular', 'Framework', '["AngularJS", "Angular.js"]', 1.0),
('Vue.js', 'Framework', '["Vue", "VueJS"]', 1.0),
('Node.js', 'Framework', '["Node", "NodeJS"]', 1.0),
('Django', 'Framework', '[]', 1.0),
('Flask', 'Framework', '[]', 1.0),
('Express.js', 'Framework', '["Express"]', 1.0),
('ASP.NET', 'Framework', '["ASP"]', 1.0),
('MySQL', 'Database', '[]', 1.0),
('PostgreSQL', 'Database', '["Postgres"]', 1.0),
('SQLite', 'Database', '[]', 1.0),
('MongoDB', 'Database', '["Mongo"]', 1.0),
('Redis', 'Database', '[]', 1.0),
('Cassandra', 'Database', '[]', 1.0),
('Oracle DB', 'Database', '["Oracle"]', 1.0),
('Microsoft SQL Server', 'Database', '["SQL Server", "MSSQL"]', 1.0),
('DynamoDB', 'Database', '[]', 1.0),
('Firebase', 'Database', '[]', 1.0),
('AWS', 'Cloud', '["Amazon Web Services"]', 1.0),
('Azure', 'Cloud', '["Microsoft Azure"]', 1.0),
('Google Cloud', 'Cloud', '["GCP"]', 1.0),
('Heroku', 'Cloud', '[]', 1.0),
('Docker', 'Cloud', '[]', 1.0),
('Kubernetes', 'Cloud', '["K8s"]', 1.0),
('Terraform', 'Cloud', '[]', 1.0),
('Jenkins', 'Cloud', '[]', 1.0),
('GitHub Actions', 'Cloud', '[]', 1.0),
('CircleCI', 'Cloud', '[]', 1.0),
('Android SDK', 'Mobile', '["Android"]', 1.0),
('iOS', 'Mobile', '[]', 1.0),
('Flutter', 'Mobile', '[]', 1.0),
('React Native', 'Mobile', '[]', 1.0),
('Xamarin', 'Mobile', '[]', 1.0),
('Jetpack Compose', 'Mobile', '[]', 1.0),
('TensorFlow', 'Data & ML', '["TF"]', 1.0),
('PyTorch', 'Data & ML', '[]', 1.0),
('Scikit-learn', 'Data & ML', '["sklearn"]', 1.0),
('Pandas', 'Data & ML', '[]', 1.0),
('NumPy', 'Data & ML', '[]', 1.0),
('Tableau', 'Data & ML', '[]', 1.0),
('Power BI', 'Data & ML', '[]', 1.0),
('Apache Spark', 'Data & ML', '["Spark"]', 1.0),
('Hadoop', 'Data & ML', '[]', 1.0),
('Kafka', 'Data & ML', '[]', 1.0),
('Git', 'DevOps & Tools', '[]', 1.0),
('GitHub', 'DevOps & Tools', '[]', 1.0),
('GitLab', 'DevOps & Tools', '[]', 1.0),
('Maven', 'DevOps & Tools', '[]', 1.0),
('Gradle', 'DevOps & Tools', '[]', 1.0),
('IntelliJ IDEA', 'DevOps & Tools', '["IntelliJ"]', 1.0),
('VS Code', 'DevOps & Tools', '["Visual Studio Code"]', 1.0),
('Postman', 'DevOps & Tools', '[]', 1.0),
('Jira', 'DevOps & Tools', '[]', 1.0),
('Confluence', 'DevOps & Tools', '[]', 1.0),
('Linux', 'DevOps & Tools', '["Bash", "Shell"]', 1.0),
('Communication', 'Soft Skill', '[]', 1.0),
('Leadership', 'Soft Skill', '[]', 1.0),
('Problem Solving', 'Soft Skill', '[]', 1.0),
('Teamwork', 'Soft Skill', '[]', 1.0),
('Agile', 'Soft Skill', '[]', 1.0),
('Scrum', 'Soft Skill', '[]', 1.0),
('Project Management', 'Soft Skill', '[]', 1.0),
('Critical Thinking', 'Soft Skill', '[]', 1.0)
ON CONFLICT(skill_name) DO NOTHING;
